require('dotenv').config();const express=require('express'),{Pool}=require('pg'),bcrypt=require('bcryptjs'),session=require('express-session'),PGStore=require('connect-pg-simple')(session),multer=require('multer'),path=require('path'),fs=require('fs'),helmet=require('helmet');
const app=express(),PORT=process.env.PORT||10000,dir=process.env.STORAGE_DIR||path.join(__dirname,'storage');fs.mkdirSync(dir,{recursive:true});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const upload=multer({dest:dir,limits:{fileSize:50*1024*1024}});
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(session({store:new PGStore({pool,tableName:'user_sessions',createTableIfMissing:true}),secret:process.env.SESSION_SECRET||'CHANGE_ME',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1209600000}}));app.use(express.static('public'));
const ROLES={admin:['view','create','edit','delete','manage_users','manage_roles'],investigator:['view','create','edit'],editor:['view','create','edit'],viewer:['view']};const can=(u,p)=>u&&ROLES[u.role]?.includes(p);const auth=(req,res,n)=>req.session.user?n():res.status(401).json({error:'Требуется вход'});const perm=p=>(req,res,n)=>can(req.session.user,p)?n():res.status(403).json({error:'Недостаточно прав'});
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,password_hash TEXT,role VARCHAR(30) NOT NULL DEFAULT 'viewer',created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS materials(id SERIAL PRIMARY KEY,title VARCHAR(160) NOT NULL,type VARCHAR(30) NOT NULL,description TEXT DEFAULT '',filename TEXT,stored_name TEXT,mime TEXT,size BIGINT,is_public BOOLEAN DEFAULT TRUE,owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS audit_log(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(80),material_id INTEGER,created_at TIMESTAMPTZ DEFAULT NOW());`);if(process.env.ADMIN_USERNAME&&process.env.ADMIN_PASSWORD){const r=await pool.query('SELECT id FROM users WHERE username=$1',[process.env.ADMIN_USERNAME]);if(!r.rowCount){await pool.query('INSERT INTO users(username,password_hash,role) VALUES($1,$2,$3)',[process.env.ADMIN_USERNAME,await bcrypt.hash(process.env.ADMIN_PASSWORD,12),'admin'])}}}
app.get('/api/me',(q,s)=>s.json({user:q.session.user||null}));
app.post('/api/register',async(q,s)=>{try{let u=String(q.body.username||'').trim(),p=String(q.body.password||'');if(!/^[A-Za-z0-9_-]{3,30}$/.test(u)||p.length<6)return s.status(400).json({error:'Логин 3-30 символов, пароль от 6.'});let r=await pool.query('INSERT INTO users(username,password_hash,role) VALUES($1,$2,$3) RETURNING id,username,role',[u,await bcrypt.hash(p,12),'viewer']);q.session.user=r.rows[0];s.json({user:r.rows[0]})}catch(e){s.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Пользователь уже существует':'Ошибка регистрации'})}});
app.post('/api/login',async(q,s)=>{let r=await pool.query('SELECT * FROM users WHERE username=$1',[q.body.username||'']);if(!r.rowCount||!r.rows[0].password_hash||!(await bcrypt.compare(String(q.body.password||''),r.rows[0].password_hash)))return s.status(401).json({error:'Неверный логин или пароль'});s.user=r.rows[0];q.session.user={id:r.rows[0].id,username:r.rows[0].username,role:r.rows[0].role};s.json({user:q.session.user})});
app.post('/api/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));
app.get('/api/materials',async(q,s)=>{let a=[],v=[],w=[];if(!q.session.user)w.push('m.is_public=true');if(q.query.q){v.push('%'+q.query.q+'%');w.push(`(m.title ILIKE $${v.length} OR m.description ILIKE $${v.length} OR COALESCE(m.filename,'') ILIKE $${v.length})`)}if(q.query.type){v.push(q.query.type);w.push(`m.type=$${v.length}`)}let r=await pool.query(`SELECT m.*,u.username owner FROM materials m LEFT JOIN users u ON u.id=m.owner_id ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY m.created_at DESC`,v);s.json({items:r.rows})});
app.post('/api/materials',auth,perm('create'),upload.single('file'),async(q,s)=>{try{let f=q.file?{name:q.file.originalname,stored:q.file.filename,mime:q.file.mimetype,size:q.file.size}:{};let r=await pool.query('INSERT INTO materials(title,type,description,filename,stored_name,mime,size,is_public,owner_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[q.body.title,q.body.type||'file',q.body.description||'',f.name||null,f.stored||null,f.mime||null,f.size||null,q.body.is_public!=='false',q.session.user.id]);await pool.query('INSERT INTO audit_log(user_id,action,material_id) VALUES($1,$2,$3)',[q.session.user.id,'create',r.rows[0].id]);s.json({item:r.rows[0]})}catch(e){s.status(500).json({error:'Ошибка сохранения'})}});
app.get('/api/materials/:id/download',async(q,s)=>{let r=await pool.query('SELECT * FROM materials WHERE id=$1',[q.params.id]);if(!r.rowCount)return s.sendStatus(404);let m=r.rows[0];if(!m.is_public&&!q.session.user)return s.sendStatus(403);if(!m.stored_name)return s.sendStatus(404);let p=path.join(dir,m.stored_name);if(!fs.existsSync(p))return s.sendStatus(404);s.download(p,m.filename||m.stored_name)});
app.delete('/api/materials/:id',auth,perm('delete'),async(q,s)=>{let r=await pool.query('SELECT * FROM materials WHERE id=$1',[q.params.id]);if(!r.rowCount)return s.sendStatus(404);let m=r.rows[0];if(m.stored_name)try{fs.unlinkSync(path.join(dir,m.stored_name))}catch{}await pool.query('DELETE FROM materials WHERE id=$1',[m.id]);s.json({ok:true})});
app.get('/api/users',auth,perm('manage_users'),async(q,s)=>s.json({users:(await pool.query('SELECT id,username,role,created_at FROM users ORDER BY id')).rows}));
app.patch('/api/users/:id/role',auth,perm('manage_roles'),async(q,s)=>{let role=q.body.role;if(!ROLES[role])return s.status(400).json({error:'Неверная роль'});if(+q.params.id===q.session.user.id&&role!=='admin')return s.status(400).json({error:'Нельзя снять admin с самого себя'});let r=await pool.query('UPDATE users SET role=$1 WHERE id=$2 RETURNING id,username,role',[role,q.params.id]);s.json({user:r.rows[0]})});
app.get('/api/audit',auth,perm('manage_users'),async(q,s)=>s.json({logs:(await pool.query('SELECT a.*,u.username FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 200')).rows}));
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('statistic-site '+PORT))).catch(e=>{console.error(e);process.exit(1)});
